apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  selector:
    app: vproapp
  ports:
  - port: 8080
    targetPort: vproapp-port
    protocol: TCP
    nodePort: 30080  # Specify the port here if needed (optional)
  type: NodePort

